# æ—¶é—´èŒƒå›´: ä»ä»Šå¤©èµ·å‘å‰å’Œå‘åè·å–çš„å¤©æ•°
days_back: 7
days_forward: 90

# å›½å®¶åˆ—è¡¨
countries:
  - US
  - JP

# äº‹ä»¶é‡è¦æ€§
volatilities:
  - NONE
  - MEDIUM
  - HIGH

# äº‹ä»¶ç±»åˆ«
categories:
  - id: "8896AA26-A50C-4F8B-AA11-8B3FCCDA1DFD"
    name: "Bond Auctions"
    emoji: ğŸ“œğŸ”¨
  - id: "FA6570F6-E494-4563-A363-00D0F2ABEC37"
    name: "Capital Flows"
    emoji: ğŸ’¸ğŸŒŠ
  - id: "C94405B5-5F85-4397-AB11-002A481C4B92"
    name: "Central Banks"
    emoji: ğŸ›ï¸âš–ï¸
  - id: "E229C890-80FC-40F3-B6F4-B658F3A02635"
    name: "Consumption"
    emoji: ğŸ›ï¸ğŸ’³
  - id: "24127F3B-EDCE-4DC4-AFDF-0B3BD8A964BE"
    name: "Economic Activity"
    emoji: ğŸ­ğŸ“ˆ
  - id: "DD332FD3-6996-41BE-8C41-33F277074FA7"
    name: "Energy"
    emoji: â›½ğŸ›¢ï¸
  - id: "7DFAEF86-C3FE-4E76-9421-8958CC2F9A0D"
    name: "Holidays"
    emoji: ğŸ“…ğŸˆ
  - id: "1E06A304-FAC6-440C-9CED-9225A6277A55"
    name: "Housing Market"
    emoji: ğŸ ğŸ”‘
  - id: "33303F5E-1E3C-4016-AB2D-AC87E98F57CA"
    name: "Inflation"
    emoji: ğŸ’µğŸš€
  - id: "9C4A731A-D993-4D55-89F3-DC707CC1D596"
    name: "Interest Rates"
    emoji: ğŸ¦ğŸ› ï¸
  - id: "91DA97BD-D94A-4CE8-A02B-B96EE2944E4C"
    name: "Labor Market"
    emoji: ğŸ‘·ğŸ’¼
  - id: "E9E957EC-2927-4A77-AE0C-F5E4B5807C16"
    name: "Politics"
    emoji: ğŸŒğŸ¤
